version: '3.9'

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
