handlebars public/components/Menu/Menu.hbs -f public/components/Menu/Menu.precompiled.js 
handlebars public/components/MenuLink/MenuLink.hbs -f public/components/MenuLink/MenuLink.precompiled.js 
handlebars public/components/Header/Header.hbs -f public/components/Header/Header.precompiled.js 
handlebars public/components/Post/Post.hbs -f public/components/Post/Post.precompiled.js 
handlebars public/components/Container/Container.hbs -f public/components/Container/Container.precompiled.js
handlebars public/components/SignupForm/SignupForm.hbs -f public/components/SignupForm/SignupForm.precompiled.js
handlebars public/components/LoginForm/LoginForm.hbs -f public/components/LoginForm/LoginForm.precompiled.js
handlebars public/components/Input/Input.hbs -f public/components/Input/Input.precompiled.js
handlebars public/components/FormButton/FormButton.hbs -f public/components/FormButton/FormButton.precompiled.js